### ISSUE TITLE
Install fails: "This command is not available in offline mode."

### ISSUE THREAD

**Issue by ecowden** [flofreud/posh-gvm#13]
We've gotten this to install successfully on several computers, but we have one that stubbornly refuses to work.

Using the [Short Script](https://github.com/flofreud/posh-gvm#via-short-script) installation method, when we get to step 2, we get, 

```
This command is not available in offline mode.
At C:\Users\...\Documents\WindowsPowerShell\Modules\posh-gvm\Utils.ps1:294 char:14
...
```

The system is connected to the Internet and the firewall is off. We can run `ping google.com` in the same PowerShell session just fine, etc.

Any suggestions?

**Comment by flofreud** [comment]
I had to update posh-gvm shortly because the API endpoint which is uses to determine online status is not available anymore. Unfortunately this also broke the selfupdate feature. 

Could be there is still a old version on the problematic computer. Try to remove the module folder under `C:\Users\...\Documents\WindowsPowerShell\Modules\posh-gvm\` and than install it again.

Otherwise try to execute the `gvm` command with the `-Verbose` flag. Probably the output yields some explanation.

**Comment by ecowden** [comment]
Apologies for the delay - the holiday calendar threw a wrench in things.

We've figured out the problem. For posterity, the issue is that we had Powershell v2.x installed instead of v3.x. Installing the "Windows Management Framework 3.0" from [here](https://www.microsoft.com/en-us/download/details.aspx?id=34595) resolved the problem.

Thanks!
